- name: Snyk
  uses: snyk/actions@0.1.1
  with:
    # Which Snyk command to run, defaults to test
    command: # optional, default is test
    # Additional arguments to pass to Snyk
    args: # optional
